version: '3.1'
services:
  etcd:
    image: quay.io/coreos/etcd
    command: etcd --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://127.0.0.1:2379
    volumes:
      - "etcd-data:/default.etcd"
    environment:
      - ETCDCTL_API=3

  etcd_config:
    build:
      context: .
      dockerfile: Dockerfile-etcd-config
    volumes:
      - "etcd-data:/default.etcd"
    environment:
      - ETCDCTL_API=3
      - ETCDCTL_ENDPOINTS=etcd:2379
    depends_on:
      - etcd

  api:
    build: .
    ports:
     - 80:9000
    environment:
      DB_USER: keeper
      DB_NAME: keeper
      DB_PORT: 5432
      DB_HOST: db

  oauth2:
    container_name: go_oauth2_server
    image: go-oauth2-server:latest
    depends_on:
      - etcd_config
      - db
    links:
      - etcd
      - db
#    build:
#      context: .
#      dockerfile: Dockerfile-oauth2
    build:
      context: ../../RichardKnop/go-oauth2-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ETCD_ENDPOINTS: "http://etcd:2379"
    command: [runserver]

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      EXTRA_DB: oauth2:oauth2,keeper:keeper

volumes:
  etcd-data:
  db-data: