version: '3.1'
services:
  etcd:
    image: quay.io/coreos/etcd
    command: etcd --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://127.0.0.1:2379
    volumes:
      - "etcd-data:/default.etcd"
    environment:
      - ETCDCTL_API=3

  etcd_config:
    build:
      context: .
      dockerfile: Dockerfile-etcd-config
    volumes:
      - "etcd-data:/default.etcd"
    environment:
      - ETCDCTL_API=3
      - ETCDCTL_ENDPOINTS=etcd:2379
    depends_on:
      - etcd

  api:
    build: .
    ports:
     - 80:9000
    environment:
      DB_PASSWORD: ""
      DB_USER: keeper
      DB_NAME: keeper
      DB_PORT: 5432
      DB_HOST: db

  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: keeper
      POSTGRES_DB: keeper

volumes:
  etcd-data:
  db-data: