version: '3.1'
services:
  api:
    build: .
    ports:
     - 9000:9000
    links:
      - "db:database"
  db:
    image: "postgres:10.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: keeper
      POSTGRES_DB: keeper

